version: '3.4'

volumes:
  countyrp-sqldata:

services:
  mssql:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234
    ports:
      - "1433:1433"
    volumes:
      - countyrp-sqldata:/var/opt/mssql

  countyrp.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:9201;http://0.0.0.0:9200
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=CountyRP.WebAPI;User Id=sa;Password=Test1234;
    ports:
      - "9200:9200"
      - "9201:9201"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  countyrp.website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:10001;http://0.0.0.0:10000
      - CmmonWebAPIBaseUrl=http://countyrp.webapi:9200
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  countyrp.forum.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:10101;http://0.0.0.0:10100
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=CountyRP.Forum.WebAPI;User Id=sa;Password=Test1234;
    ports:
      - "10100:10100"
      - "10101:10101"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  countyrp.services.site:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:10501;http://0.0.0.0:10500
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=CountyRP.Services.Site;User Id=sa;Password=Test1234;
    ports:
      - "10500:10500"
      - "10501:10501"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  countyrp.services.forum:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:10511;http://0.0.0.0:10510
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=CountyRP.Services.Forum;User Id=sa;Password=Test1234;
    ports:
      - "10510:10510"
      - "10511:10511"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro