version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest

  countyrp.webapi:
    image: ${DOCKER_REGISTRY-}countyrpwebapi
    build:
      context: .
      dockerfile: CountyRP.WebAPI/Dockerfile
    depends_on:
      - mssql

  countyrp.website:
    image: ${DOCKER_REGISTRY-}countyrpwebsite
    build:
      context: .
      dockerfile: CountyRP.WebSite/Dockerfile

  countyrp.forum.webapi:
    image: ${DOCKER_REGISTRY-}countyrpforumwebapi
    build:
      context: .
      dockerfile: Forum/CountyRP.Forum.WebAPI/Dockerfile
    depends_on:
      - mssql

  countyrp.services.site:
    image: ${DOCKER_REGISTRY-}countyrpservicesite
    build:
      context: .
      dockerfile: Services/Site/Site.API/Dockerfile
    depends_on:
      - mssql

  countyrp.services.forum:
    image: ${DOCKER_REGISTRY-}countyrpserviceforum
    build:
      context: .
      dockerfile: Services/Forum/Dockerfile
    depends_on:
      - mssql

  countyrp.services.game:
    image: ${DOCKER_REGISTRY-}countyrpservicegame
    build:
      context: .
      dockerfile: Services/Game/Game.API/Dockerfile
    depends_on:
      - mssql

  countyrp.services.logs:
    image: ${DOCKER_REGISTRY-}countyrpservicelogs
    build:
      context: .
      dockerfile: Services/Logs/Logs.API/Dockerfile
    depends_on:
      - mssql

  countyrp.gateways.adminpanel.api:
    image: ${DOCKER_REGISTRY-}countyrpgatewayadminpanelapi
    build:
      context: .
      dockerfile: Gateways/AdminPanel/AdminPanel.API/Dockerfile
