version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest

  countyrp.webapi:
    image: ${DOCKER_REGISTRY-}countyrpwebapi
    build:
      context: .
      dockerfile: CountyRP.WebAPI/Dockerfile
    depends_on:
      - mssql

  countyrp.website:
    image: ${DOCKER_REGISTRY-}countyrpwebsite
    build:
      context: .
      dockerfile: CountyRP.WebSite/Dockerfile

  countyrp.forum.webapi:
    image: ${DOCKER_REGISTRY-}countyrpforumwebapi
    build:
      context: .
      dockerfile: Forum/CountyRP.Forum.WebAPI/Dockerfile
    depends_on:
      - mssql

  countyrp.services.site:
    image: ${DOCKER_REGISTRY-}countyrpservicesite
    build:
      context: .
      dockerfile: Services/Site/Dockerfile
    depends_on:
      - mssql

  countyrp.services.forum:
    image: ${DOCKER_REGISTRY-}countyrpserviceforum
    build:
      context: .
      dockerfile: Services/Forum/Dockerfile
    depends_on:
      - mssql
